title: MacCoss Lab
description: Biological Mass Spectrometry Laboratory
url: "https://maccosslab.github.io"
baseurl: ""

# Site settings
author: Michael MacCoss
email: maccoss@uw.edu
institution: University of Washington
department: Department of Genome Sciences

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - pages/positions.md
  - pages/about.md
  - pages/research.md
  - pages/publications.md
  - pages/software.md
  - pages/people.md
  - pages/news.md
  - pages/resources.md
  - pages/funding.md
  - pages/contact.md

# Collections
collections:
  people:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md